### PR TITLE
Symfony 5 compatibility

### PR DESCRIPTION
**Pull request by natewiebe13**
This PR adds Symfony 5 compatibility as well as fixes an issue with Symfony 3. This was tested with Symfony 3.4, 4.4, and 5.0 and Twig 1, 2, and 3.

### CODE REVIEW

**Comment by anyt** [comment]
Thank you, Nate!

We really appreciate that you found the extension useful and even making it better.
_Internal ticket id #BB-18735_.

**Comment by natewiebe13** [comment]
@anyt No problem! We're wanting to start adding this to our projects. Any idea on timeline for getting this merged in and a version released?

**Comment by anyt** [comment]
I'm going to check it and merge it if everything is ok until the end of the week.

**Comment by anyt** [comment]
The pull request has been merged, and the new version of a package with Symfony 5 support is released.

Thank you for your contribution, @natewiebe13!

**Pull request closed without merging**
